services:
  controlled-vocabolary-interface:
    image: controlled-vocabolary-interface:prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3000"
    environment:
      # GraphDB Connection Configuration
      GRAPHDB_BASE_URL: "https://dev-graphdb.swissgeol.ch"      
      GRAPHDB_USERNAME: ""
      GRAPHDB_PASSWORD: ""
      
      # Repository IDs per vocabulary
      CHRONOSTRATIGRAPHY_REPO_ID: "chronostratigraphy_swisstopo_public_core"
      TECTONICUNITS_REPO_ID: "tektonik_swisstopo_public_core"
      LITHOSTRATIGRAPHY_REPO_ID: "lithostratigraphy_swisstopo_public_core"
      LITHOLOGY_REPO_ID: "lithology_swisstopo_public_core"
      
      # Vocabulary Prefix Base URL (for SPARQL queries)
      VOCABULARY_PREFIX_URL: "https://dev-lexic.swissgeol.ch"

      GITHUB_OWNER: swisstopo

      CHRONOSTRATIGRAPHY_REPO_SLUG: swissgeol-lexic-vocabulary-chronostratigrafie
      TECTONICUNITS_REPO_SLUG: swissgeol-lexic-vocabulary-tektonik
      LITHOSTRATIGRAPHY_REPO_SLUG: swissgeol-lexic-vocabulary-lithostratigrafie
      LITHOLOGY_REPO_SLUG: swissgeol-lexic-vocabulary-lithologie